### PR TITLE
Add ocsort c++ and example verify from inference yolov8

### PR DESCRIPTION
**Pull request by phongans**
This project is the C++ version of OC-SORT (OC-SORT: Observation-Centric SORT on video Multi-Object Tracking), and it utilizes the Eigen library for matrix operations. The project primarily refers to the official Python implementation of OC_SORT. The goal is to maintain consistency with the official Python version in terms of code logic and variable naming conventions. The linear assignment algorithm utilizes the open-source library Lap. The improved Kalman Filter in OC-SORT is implemented solely using the Eigen library. Support cuda 11.7 and tensort 8.5.1.7

### CODE REVIEW

**Comment by phongans** [comment]
image-detection

**Comment by phongans** [comment]
@noahcao can you help?

**Comment by Postroggy** [comment]
WTF，you @phongans  are a really poor guy, stole my code? checkout this : [my repo](https://github.com/Postroggy/OC_SORT_CPP)  
The  code you provided is mostly borrowed from my project. you a stupid nasty cunt!

**Comment by Postroggy** [comment]
@phongans  FUCK you ! STOLE my code without Indicate the source! THE CODE AUTHOR IS ME! STUPID BITCH! @phongans

**Comment by noahcao** [comment]
@phongans Could you please clarify the claim about authorship by @Postroggy here? In your code, you does not state about the reference of your code from other codebases, such as [Postroggy's repo](https://github.com/Postroggy/OC_SORT_CPP). Thanks.

**Comment by noahcao** [comment]
Hi @Postroggy, I will make sure that the code author will get their deserved acknowledgment and credit. But please be patient and avoid using bad words here. Thanks so much! I also apologize that I hadn't noticed the potential re-use of code.

**Comment by Postroggy** [comment]
@phongans  I code the project for about 4 month. and you just copy it and modify add some file, you not even want to change the variable name and namespace. How ridiculous.

**Comment by phongans** [comment]
@Postroggy First of all, we should treat each other with respect.

Secondly, I will investigate whether my teammate has used your code and made further improvements. I will check it exactly as you mentioned. If it's true, I will refer it to the original author. We strive to collaborate and make everything better.

@noahcao  Thirdly, thank you for evaluating our code, and we will do some revisions and provide a comprehensive update.

**Comment by Postroggy** [comment]
@phongans such a team just Appropriate others' work. you can `diff` the code. I can guarantee it has more than 80% coincidence.  yes you can improve the code and help the community , but you know my project is licensed with MIT license.

**Comment by phongans** [comment]
@Postroggy I will check and guide you to the folder containing this code

**Comment by phongans** [comment]
@Postroggy This code is an example of OCSORT in C++, validated by yolov8.

**Comment by Postroggy** [comment]
you code :[url](https://github.com/noahcao/OC_SORT/tree/7a2a92fe4d32c0169734b1bd68c45b468e011e55/deploy/OCSort/cpp)
mine: [url](https://github.com/Postroggy/OC_SORT_CPP/)
Add the code author is me where your team used my work. (MIT) by the way, you teammate sucks.

**Comment by noahcao** [comment]
Hi @phongans , thanks for the timely reply. I noticed some code overlap between the two versions of the code and also their differences. It is a good practice to the community that any re-used code, if any, and doc are noted and acknowledged. It is encouraged to have review of your code's resources and originality! Thanks.

**Comment by phongans** [comment]
@Postroggy It is also my responsibility. Thank you

**Comment by phongans** [comment]
@phongans The use and modification of code without the consent of the original author can lead to serious misunderstandings

**Comment by noahcao** [comment]
Hi @phongans Thanks for the reply. Please let me know if you have more knowledge about the code resources. After some review and comparison of the code, if no further explanations are provided, I will also list @Postroggy as one of the contributors of the C++ support of OC-SORT here.

**Comment by Postroggy** [comment]
已经收到您发送的邮件，有空处理了再联系您。郭跃琪

**Comment by phongans** [comment]
I added author at https://github.com/noahcao/OC_SORT/pull/100

**Comment by noahcao** [comment]
Thank you @phongans for the contribution! Also, thanks to @Postroggy for the original version of support (acknowledged in the [readme](https://github.com/noahcao/OC_SORT/tree/master/deploy/OCSort/cpp)).

**Pull request merged**
